### ISSUE TITLE
Is this API Support the Ordering process to amazon?

### ISSUE THREAD

**Issue by BillDavid07** [tuurbo/amazon-payment#1]
Hi,

I just want to ask if this API support the functionality of posting order  and add a payment to amazon through my website and not on amazon itself. like this api https://docs.zincapi.com/#place-an-order.

Thanks & regards,
JeromeD

**Comment by tuurbo** [comment]
This just allows the customer to pay with their amazon account on your website. I'm not maintaining this lib at the moment so I recommend to you take a look at https://github.com/amzn/amazon-pay-sdk-php
